### PR TITLE
YSwift docs

### PR DESCRIPTION
**Pull request by heckj**
fleshing out of documentation for the YSwift overlay layer

### CODE REVIEW

**Comment by heckj** [comment]
@nugmanoff give the various documentation updates a read through - let me know if anything looks obviously or horribly wrong.

There's a few places where I think we have partial code in there that isn't actually fully fleshed out, specifically in YText. I did my best with what I saw in places, but that may be something we want to consider making internal/private for this first cut over the API. Let know what you think, and please feel free to suggest wording changes or anything that improves clarity for YSwift users.

**Comment by nugmanoff** [comment]
You did an amazing job, Joe! Absolutely no comments from my side on what you've written. Pure bliss🤌

Some things we might want to add:

1. More examples with explanations on how to use this thing – I've seen you included how to sync remote and local document – that's perfect! Maybe just few more things like:

```swift
let localDocument = YDocument()
let remoteDocument = YDocument() 

let localArray: [Int] = localDocument.getOrCreateArray("array")
let remoteArray: [Int] = remoteDocument.getOrCreateArray("array")

// and then show here example of syncing them together initially
// follow by showing how they "diverge" 
// and how they get merged back again
// and just show the state of the arrays at each step

```

2. Explaining parts about implicit vs explicit transactions and why YArray, YText & etc can't be instantiated directly and should be created by factory methods on YDocument.

**Comment by heckj** [comment]
I've added in an article that basically reproduces what you originally included in the testing for YDocument, and then referenced the To Do list example from within the article to this repo (or what this repo will be called down the road...)

I'll follow up online (Discord) to get more details about what you'd like to see re: transactions and more explored reasoning being included for how to correctly use the various classes.

**Comment by nugmanoff** [comment]
You are so great at writing, Joe! Amazing work. LGTM👍

**Review by nugmanoff — APPROVED** [review]

**Pull request merged**
