### PR TITLE
Rearrange for yswift

### LINKED ISSUE #8: Consumption goal for the library
I'd like to see the end result of what we create here be usable through Swift Package Manager - the idea being that someone could add a dependency to "Y-CRDT" (or whatever we call the module), and have that automatically pull in the dependencies that we create and make available from this repo - the swift overlay and the underlying static C libraries.

The target for something like this would be to allow a developer to add a dependency to their Package.swift file:

```
dependencies: [
        .package(url: "https://github.com/y-crdt/y-uniffi", from: "0.1.0"),
],
```

and from there be able to add an import that makes YDoc available in the code:
```swift
We might even want to think about what we want the name of this module to be in terms of swift import - so from the call sites you do something akin to:

```swift
import YCRDT

let doc = YDoc()
```

Along these lines, what do we want the various names to be that are used here? There are three we need to nail down:

1) repository to use for the C library/XCFramework dependency (currently `y-uniffi`)
2) a repository for the swift overlay dependency (also currently `y-uniffi`, but only because it's all in the same place - I don't know how possible it is to have two different dependencies served from the same repository)
3) The module name that a developers imports to use the library (currently `YSwift` - but I'd like to suggest `YCRDT` instead)

### PR DESCRIPTION
**Pull request by heckj**
resolves #8 

predicated (based) off the content in #27 being merged before this

### CODE REVIEW

**Comment by heckj** [comment]
@nugmanoff - I'm currently working from two separate locations for the swift files - the generated stuff still in the `lib/swift` directory, and I moved all the `YSwift` pieces up to the very top. I've (at the moment) disabled the Tuist pieces as I wasn't super familiar with how to re-arrange it for a local "swift package", but I'm hoping that we can re-enable that pretty quickly to maintain the example code bases that use the underlying `YSwift`  library.

The docs being generated into the GitHub pages are only for the raw-generated pieces right now. I need/want to add Documentation for all the nice bits within the higher level YSwift library and get it set so that those documentation pages are generated as well.

WIth this structure, we *should* be able to submit this to the Swift Package Index as soon as we're ready to tag and cut a `0.1.0` release, although I suspect using the "local reference to an XCFramework" trick will mean that we'll need to host our own documentation on GitHub pages, since the automated process they use (`swift-docc-plugin`) has a nasty bug that causes automatic doc generation to fail with the scenario we're using.

**Comment by heckj** [comment]
@nugmanoff I'm having a rough time getting Tuist to recognize a local Package.swift project as a dependency. I've tried updating things, going through docs, etc. - but was hoping that perhaps you knew a bit more and how to wade out from this.

The error I'm getting on `tuist generate` is:

```
/Users/heckj/src/y-uniffi/examples/Project.swift:
TUIST_MANIFEST_START
{"schemes":[],"additionalFiles":[],"resourceSynthesizers":[{"extensions":["strings","stringsdict"],"parser":"strings","templateType":{"defaultTemplate":{"resourceName":"Strings"}}},{"extensions":["xcassets"],"parser":"assets","templateType":{"defaultTemplate":{"resourceName":"Assets"}}},{"extensions":["plist"],"parser":"plists","templateType":{"defaultTemplate":{"resourceName":"Plists"}}},{"extensions":["ttc","ttf","otf"],"parser":"fonts","templateType":{"defaultTemplate":{"resourceName":"Fonts"}}}],"organizationName":"y-crdt","packages":[],"targets":[{"deploymentTarget":{"iOS":{"devices":1,"supportsMacDesignedForIOS":true,"targetVersion":"15.0"}},"coreDataModels":[],"bundleId":"y-crdt.swift.example.document-editing","launchArguments":[],"additionalFiles":[],"product":"app","sources":{"globs":[{"excluding":[],"glob":{"type":"relativeToManifest","pathString":"Examples\/DocumentEditing\/**"}}]},"buildRules":[],"infoPlist":{"extendingDefault":{"with":{"NSLocalNetworkUsageDescription":{"string":{"_0":"YSwiftExample needs to use your phone’s data to discover devices nearby"}},"UILaunchStoryboardName":{"string":{"_0":"LaunchScreen"}}}}},"resources":{"resources":[{"glob":{"pattern":{"type":"relativeToManifest","pathString":"Examples\/DocumentEditing\/LaunchScreen.storyboard"},"excluding":[],"tags":[]}}]},"platform":"ios","scripts":[],"dependencies":[{"external":{"name":"YSwift"}}],"environment":{},"name":"DocumentEditing"},{"deploymentTarget":{"iOS":{"devices":1,"supportsMacDesignedForIOS":true,"targetVersion":"15.0"}},"coreDataModels":[],"bundleId":"y-crdt.swift.example.todolist","launchArguments":[],"additionalFiles":[],"product":"app","sources":{"globs":[{"excluding":[],"glob":{"type":"relativeToManifest","pathString":"Examples\/Todolist\/**"}}]},"buildRules":[],"infoPlist":{"extendingDefault":{"with":{"NSLocalNetworkUsageDescription":{"string":{"_0":"TodoListExample needs to use your phone’s data to discover devices nearby"}},"UILaunchStoryboardName":{"string":{"_0":"LaunchScreen"}}}}},"resources":{"resources":[{"glob":{"pattern":{"type":"relativeToManifest","pathString":"Examples\/Todolist\/LaunchScreen.storyboard"},"excluding":[],"tags":[]}}]},"platform":"ios","scripts":[],"dependencies":[{"external":{"name":"YSwift"}}],"environment":{},"name":"TodoListExample"}],"options":{"automaticSchemesOptions":{"enabled":{"targetSchemesGrouping":{"byNameSuffix":{"build":["Testing","Mocks","Implementation","Interface"],"run":["Demo","App"],"test":["UITests","IntegrationTests","SnapshotTests","Tests"]}},"testingOptions":0,"codeCoverageEnabled":false}},"disableShowEnvironmentVarsInScriptPhases":false,"disableBundleAccessors":false,"disableSynthesizedResourceAccessors":false,"textSettings":{}},"name":"YSwiftExamples"}
TUIST_MANIFEST_END
Unable to load manifest at /Users/heckj/src/y-uniffi/examples/Project.swift
Did not find property with name name in the JSON represented by:

{"swiftPackageManager":{"baseSettings":{"base":{},"configurations":[{"name":{"rawValue":"Debug"},"variant":"debug","settings":{}},{"name":{"rawValue":"Release"},"variant":"release","settings":{}}],"defaultSettings":{"recommended":{"excluding":[]}}},"productTypes":{},"targetSettings":{},"projectOptions":{},"packages":[{"local":{"path":{"type":"relativeToManifest","pathString":".."}}}]},"platforms":["ios"]}

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

This seems to be wanting a name for the dependency, but the exposed structures only allow for declaring a path - I would guess expecting to look up a relevant name once it's loaded. If we had a release, I'd make this a fully externalized package reference and not care - but since we're before that I'm trying to work with whatever is local.

Any ideas here?

**Comment by nugmanoff** [comment]
Pushed the fix. It was due to `dependencies` being declared not in the `Dependencies.swift` file. That's why it didn't recognize its "name".

From [Tuist docs](https://docs.tuist.io/guides/third-party-dependencies/):

> External dependencies are declared in a Dependencies.swift file in your project's Tuist directory at the project's root.

The error message was not helpful though, I just basically diffed working old setup & this one with me eyes to catch any difference. That's how I arrived at this fix.

I am thinking now that maybe Tuist is just unnecessarily overcomplicating things – and we better remove it?

The biggest reason why I love using it – is being able to completely gitignore *.xcproj/*.xcworkspace files and never deal with nasty merge conflicts ever again.

**Comment by heckj** [comment]
I've no problem keeping it - it's a good way to handle the examples, even if I stumbled through the details of how to get the dependency in place. Thank you for the fix!

It's highlighting an error in one of the example projects now, which is perfect - we can follow up and  get them aligned with the current state of YSwift.

**Pull request merged**
